final String CONSUMER_KEY    = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
final String CONSUMER_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
final String ACCESS_TOKEN    = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
final String ACCESS_SECRET   = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";